include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
  errors:
    # freezed + json_serializable place JsonKey on factory params which the
    # analyzer flags but works fine at codegen time. Cosmetic.
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_classes_with_only_static_members: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    use_build_context_synchronously: false
